# Generated by Django 5.1.4 on 2025-02-01 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_name", models.CharField(max_length=100)),
                ("client_quartier", models.CharField(max_length=100)),
                ("client_city", models.CharField(max_length=100)),
                ("client_country", models.CharField(max_length=100)),
                ("client_phone", models.CharField(max_length=100)),
                ("client_mail", models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.TextField()),
                ("number", models.CharField(max_length=100)),
                ("echeance", models.DateField()),
                ("tax", models.BooleanField()),
                (
                    "type_tax",
                    models.CharField(
                        choices=[("TVA", "TVA"), ("ISB", "ISB")], max_length=100
                    ),
                ),
                ("payment_mode", models.TextField()),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wageslip.client",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Designation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("designation_title", models.TextField()),
                ("designation_details", models.TextField()),
                (
                    "designation_unit_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("designation_quantity", models.IntegerField()),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="designations",
                        to="wageslip.invoice",
                    ),
                ),
            ],
        ),
    ]
