# Generated by Django 5.1.4 on 2025-02-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wageslip", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="date",
            field=models.DateField(auto_now=True),
        ),
    ]
