# Generated by Django 5.1.4 on 2025-02-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wageslip", "0002_invoice_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="name",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="type_tax",
            field=models.CharField(
                choices=[("TVA", "TVA"), ("None", "None"), ("ISB", "ISB")],
                max_length=100,
            ),
        ),
    ]
