# Generated by Django 5.1.4 on 2025-03-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wageslip", "0003_invoice_name_alter_invoice_type_tax"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="montant_avance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="designation",
            name="designation_unit_price",
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
