# Generated by Django 5.1.4 on 2025-03-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wageslip", "0004_invoice_montant_avance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="stamp",
            field=models.BooleanField(default=True),
        ),
    ]
