# Generated by Django 5.1.4 on 2025-04-04 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wageslip", "0005_invoice_stamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="client_city",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="client_country",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="client_mail",
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="client_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="client_phone",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="client_quartier",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="designation",
            name="designation_details",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="echeance",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="tax",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="topic",
            field=models.TextField(null=True),
        ),
    ]
